public record CandidateProfileDto(
    int Id,
    int UserId, 
    string FirstName,
    string LastName,
    string? PhoneNumber,
    DateTime? DateOfBirth,
    string? City,
    string? Country,
    string? PhotoUrl,
    string? CVUrl,
    string? CoverLetterUrl, 
    string? Summary,
    string? LinkedInUrl,
    string? GitHubUrl, 
    List<CandidateSkillDto> Skills,
    List<ExperienceDto> Experiences,
    List<EducationDto> Educations);